apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-server-exporter-go
  labels:
    k8s-app: metrics-server-exporter-go
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: metrics-server-exporter-go
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: metrics-server-exporter-go
    spec:
      serviceAccountName: metrics-server-exporter-go
      containers:
      - name: metrics-server-exporter-go
        image: regsitry.carlosmalucelli.com/metrics-server-exporter-go:XXVERSIONXX
        imagePullPolicy: Always
        ports:
        - containerPort: 8484
          protocol: TCP
      restartPolicy: Always
