apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "8484"
    prometheus.io/scrape: "true"
  name: metrics-server-exporter-go
  labels:
    k8s-app: metrics-server-exporter-go
spec:
  ports:
  - port: 8484
    protocol: TCP
    targetPort: 8484
  selector:
    k8s-app: metrics-server-exporter-go
